--- #YAML:1.0
name: POE
version: 0.28
author:
  - ~
abstract: |-
  portable multitasking and networking framework for Perl
license: perl
requires:
  Carp: 0
  Exporter: 0
  Filter::Util::Call: 1.04
  IO: 0
  POSIX: 0
  Socket: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DB:
    file: lib/Devel/Trace.pm
    version: 1.8
  ExtUtils::AutoInstall:
    file: lib/ExtUtils/AutoInstall.pm
    version: 0.52
  MY:
    file: lib/Makefile-5004.pm
  MyOtherFreezer:
    file: lib/MyOtherFreezer.pm
    version: 1.3
  Null:
    file: lib/Devel/Null.pm
    version: 1.2
  Test::Harness:
    file: lib/Test/Harness.pm
    version: 2.26
  Test::Harness::Assert:
    file: lib/Test/Harness/Assert.pm
    version: 0.01
  Test::Harness::Iterator:
    file: lib/Test/Harness/Iterator.pm
    version: 0.01
  Test::Harness::Iterator::ARRAY:
    file: lib/Test/Harness/Iterator.pm
    version: 0.01
  Test::Harness::Iterator::FH:
    file: lib/Test/Harness/Iterator.pm
    version: 0.01
  Test::Harness::Straps:
    file: lib/Test/Harness/Straps.pm
    version: 0.14
  TestSetup:
    file: lib/TestSetup.pm
    version: 1.9
  Trace:
    file: lib/Devel/Trace.pm
    version: 1.8
generated_by: Module::Build version 0.22
